#!/bin/sh
set -e

if [ "$1" = "configure" ] ; then
  adduser --system --home /var/lib/moasdawiki --disabled-login moasdawiki
fi

# Workaround for JSVC bug that doesn't find the JVM
if [ ! -d "/usr/lib/jvm/java-11-openjdk-amd64/lib/amd64/server" ]
then
  sudo mkdir /usr/lib/jvm/java-11-openjdk-amd64/lib/amd64
  sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64/lib/server /usr/lib/jvm/java-11-openjdk-amd64/lib/amd64/server
fi

#DEBHELPER#
