image: java:8-jdk

include:
  - template: Dependency-Scanning.gitlab-ci.yml

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

after_script:
  - echo "CI finished"

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew --no-daemon assemble
  artifacts:
    expire_in: never
    paths:
      - build/distributions/*.zip
  only:
    - tags

test:
  stage: test
  script:
    - ./gradlew --no-daemon check
  artifacts:
    expire_in: 1 week
    paths:
      - build
    reports:
      junit: build/reports/tests/test/junitreports/*
