image: java:8-jdk

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/distributions/*.zip
  only:
    - tags

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    reports:
      junit: build/reports/tests/test/junitreports/**/TEST-*.xml

after_script:
  - echo "CI finished"
